### ISSUE TITLE
cleaned data

### ISSUE THREAD

**Issue by ifangcheng** [XiaohangZhan/cdp#3]
Just wondering whether the CLEANED data  used in the paper ("we clean up official training set and crawl images of more identities, producing about 7M images with 385 K identities") will be released for the public research in future?   Many Thanks!

**Comment by XiaohangZhan** [comment]
Unfortunately it will not be released since it belongs to my colleagues' contribution. Alternatively you can use another cleaned MS1M called "emore" by DeepInsight. The project is here: `https://github.com/deepinsight/insightface`. See README --> Recent Update --> 2018.05.16.
According to our experiments, this dataset is better than ours, you can try on it.
